server:
  port: 7003
spring:
  application:
    name: mall-stock
  nacos:
    discovery:
      server-addr: http://localhost:8848
  redis:
    host: 172.30.4.43
    port: 6379
    password:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.3.107:3307/sharding_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: export

#eureka:
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#  client:
#    register-with-eureka: true #注册到Eureka的注册中心
#    fetch-registry: true #获取注册实例列表
#    service-url:
#      defaultZone: http://192.168.75.29:6001/eureka/ #配置注册中心地址

#配置文件开启OpenFeign使用OkHttp作为底层的client
feign:
  okhttp:
    enabled: true

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

logging:
  level:
    root: info
    com.mall.cloud.mapper: debug