
spring:
  application:
    name: eureka-server

server:
  port: 6001 #指定运行端口
eureka:
  instance:
    hostname: 127.0.0.1 #指定主机地址
  client:
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
    service-url:
      defaultZone: http://192.168.249.129:6001/eureka/,http://192.168.249.130:6001/eureka/
  server:
    enable-self-preservation: false #关闭保护模式




