server:
  port: 7001
spring:
  application:
    name: mall-oauth2-server

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://192.168.75.29:6001/eureka/ #配置注册中心地址


#配置文件开启OpenFeign使用OkHttp作为底层的client
feign:
  okhttp:
    enabled: true

auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: malljelly
  clientSecret: 123456


encrypt:
  key-store:
    location: classpath:/malljelly.jks
    secret: malljelly
    alias: malljelly
    password: malljelly
