server:
  port: 7001
spring:
  application:
    name: mall-auth
  redis:
    host: 172.30.4.43
    port: 6379
    password:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.3.107:3307/sharding_0?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: export


eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true #注册到Eureka的注册中心
    fetch-registry: true #获取注册实例列表
    service-url:
      defaultZone: http://192.168.249.129:6001/eureka/,http://192.168.249.130:6001/eureka/

#配置文件开启OpenFeign使用OkHttp作为底层的client
feign:
  okhttp:
    enabled: true

auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: malljelly
  clientSecret: 123456


encrypt:
  key-store:
    location: classpath:/malljelly.jks
    secret: malljelly
    alias: malljelly
    password: malljelly

